name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'imatrix-website/apps/web/package-lock.json'

      - name: Install dependencies
        run: |
          cd imatrix-website/apps/web
          npm ci

      - name: Build
        run: |
          cd imatrix-website/apps/web
          npm run build

      - name: List build files
        run: |
          ls -la imatrix-website/apps/web/dist/
          echo "--- index.html content preview ---"
          head -10 imatrix-website/apps/web/dist/index.html || echo "No index.html found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./imatrix-website/apps/web/dist